emCase/device/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^visual$', views.visualization, name='visualization'),
    url(r'^view_device/(?P<id_number>\d+)$', views.view_device, name='view_device'),
    url(r'^$', views.index, name='index'),    
]

emCase/emCase/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^location/', include('location.urls')),
    url(r'^device/', include('device.urls')),
    url(r'^', include('location.urls')),
]

emCase/location/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#url(r'^view_device/(?P<id_number>\d+)$', views.view_device, name='view_device'),
    url(r'^location$', views.view_location, name='location'),    
    url(r'^stop$', views.stop, name='stop'),    
    url(r'^$', views.run_location, name='index'),    
    url(r'^view_locations$', views.view_location, name='view_location'),
]

emCase/device/models.py
from django.db import models

# Create your models here.

class Device(models.Model):
    type_choice = (
            ("FD", "Fire Distinguisher"),
            ("MK", "Medi Kit"),
            ("FB", "Fuse box"),
            ("O", "Other")
            )

    status_choice = (
            ("Working", "Working"),
            ("Problem", "Problem"),
            ("Broken", "Broken"),
            ("Triggered", "Triggered"),
            ("Other", "Other")
            )

    id_number = models.IntegerField(unique=True, verbose_name="Serial Number of IoT")
    human_readable_name = models.CharField(max_length=100, verbose_name="Human readable name")
    insert_date = models.DateTimeField(verbose_name="Insert Date")
    type_of_device = models.CharField(max_length=100, choices=type_choice, verbose_name="Type of a device")
    last_check_date = models.DateTimeField(verbose_name="Last Check date")
    location = models.CharField(max_length=100, verbose_name="GPS Location")
    description_of_device = models.TextField(verbose_name = "Description of a device")
    description_of_content = models.TextField(verbose_name = "Description of a content")
    status = models.CharField(max_length=100, choices=status_choice, verbose_name = "Status")
    posted = models.BooleanField(default=False, verbose_name="Posted")
    ip_addrr = models.GenericIPAddressField(blank=False, verbose_name="IP addrres")
    port = models.IntegerField(verbose_name="Port")

    

emCase/location/models.py
from django.db import models

# Create your models here.
class Location(models.Model):
    
    lng = models.FloatField(verbose_name="Longitude")
    lat = models.FloatField(verbose_name="Latitude")
    timestamp = models.DateTimeField(verbose_name="Time", auto_now_add=True)

emCase/location/forms.py
from django import forms

class LocationForm(forms.Form):
    lng = forms.FloatField(label="Longitude")
    lat = forms.FloatField(label="Latitude")
    command = forms.CharField(max_length=50, label="Command",widget = forms.HiddenInput())

emCase/device/views.py
from django.shortcuts import render, HttpResponse
from device.models import Device
from django.shortcuts import get_object_or_404

# Create your views here.
def index(request):
    return render(request, 'index.html', {'devices' : Device.objects.all(), 'test': "QWERTYUIOP"})

def view_device(request, id_number):
    #id_number = request.GET.get("id_number")
    device = get_object_or_404(Device, id_number=id_number)
    lat = device.location.split(",")[0].strip()
    lng = device.location.split(",")[1].strip()
    return render(request, 'view_device.html', {'device' : device, 'lng': lng, 'lat': lat })	
    
def visualization(request):

    from device.models import Device
    from django.db.models import Count
    counts = [((val["type_of_device"], val["type_of_device__count"])) for val in Device.objects.values("type_of_device").annotate(Count("type_of_device"))]

    r = get_plots(counts)
    import plotly.tools as tls

    bar = tls.get_embed(r)
    return render(request, 'visual.html', {"type": bar })

def get_plots(counts):
    import plotly.plotly as py
    import plotly.graph_objs as go
    import plotly.tools as tls
    py.sign_in('kotrfa', 'etp2llol2i') 
    # (1) Two lists of numbers
    print(counts)

    x1 = [x for x,y in counts]
    y1 = [y for x,y in counts]

    data = [go.Bar(x=x1, y=y1)]
    
    layout = go.Layout(
        title='Type of device',
    )

    return py.plot(data, filename='type of device', auto_open=False)

emCase/location/views.py
from django.shortcuts import render

# Create your views here.

from location.models import Location
from device.models import Device
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

from .forms import LocationForm

# Create your views here.
def index_location(request):
    return render(request, 'index_location.html', { })

def stop(request):
    from .run_devices import megafunc
    megafunc(0,0, "stop all")
    return render(request, "stop.html")
    
from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def run_location(request):
    if request.method == "POST":
        form = LocationForm(request.POST)
        
        if form.is_valid():
            # RUN devices!
            # from run_devices import ...
            from .models import Location
            _lng = form.cleaned_data["lng"]
            _lat = form.cleaned_data["lat"]
            Location.objects.create(lng=_lng, lat=_lat)
            print("CREATED LOCATION!!!")

            _command = form.cleaned_data["command"]
            from .run_devices  import megafunc
            res, ids = megafunc(_lng, _lat, _command)
            shrinked_d = {}
            for device in ids:
                lat = device.location.split(",")[0].strip()
                lng = device.location.split(",")[1].strip()
                shrinked_d[device.id_number] = { 'lat':lat, 'lng':lng, 'name':device.human_readable_name, 'type':device.type_of_device }                
            return render(request, 'activated.html', {'log' :  res, 'devices': shrinked_d})
    else:
        form = LocationForm()
    return render(request, 'loc_form.html', {'form' : form})

def view_location(request):
    devices = Device.objects.all()
    shrinked_d = {}
    for device in devices:
        lat = device.location.split(",")[0].strip()
        lng = device.location.split(",")[1].strip()
        shrinked_d[device.id_number] = { 'lat':lat, 'lng':lng, 'name':device.human_readable_name, 'type':device.type_of_device }        
    return render(request, 'view_location.html', {'devices' : shrinked_d})

emCase/device/templates/index.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Device Index' }} {% endblock %}

{% block content %}


	<style type="text/css">
		.header_img{
			filter:blur(5px);
			-webkit-filter: grayscale(100%); /* Chrome, Safari, Opera */
    		filter: grayscale(100%);
		}
		.header_img:hover{
			filter:blur(1px);
			-webkit-filter: grayscale(0%); /* Chrome, Safari, Opera */
    		filter: grayscale(0%);
		}
	</style>
	{% 	if devices %}
	<section id="four" class="wrapper alt style1">
		<div class="inner">
			<!-- <h2 class="major">Life sucks</h2>
			<p>All devices</p>-->
			<section class="features">
				{% 	for device in devices %}
					<article>
						<a href="/device/view_device/{{ device.id_number }}" class="image header_img">
							<img src="{{ STATIC_URL }}/images/{% if device.type_of_device == "FD" %}ext.jpg{% elif device.type_of_device == "MK" %}med.jpg{% else %}fuse.jpg{% endif %}" alt="">
						</a>						
						<h3 class="major">{{ device.human_readable_name }}</h3>
						<p>{{ device.description }}
						<a href="/device/view_device/{{ device.id_number }}" class="special">Learn more</a>
					</article>
				{% 	endfor %}
			</section>
			<ul class="actions">
				<li><a href="#" class="button">Browse All</a></li>
			</ul>
		</div>
	</section>


		
	{% 	endif %}

{% endblock %}

emCase/device/templates/view_device.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Device Index' }} {% endblock %}
{% block content %}
	<section id="two" class="wrapper alt spotlight style2">
		<style>
			#map {
				min-height: 100px;
        		/*height: 100%;*/
        		width: 100%;
        		border-radius: 50%;
      		}
    	</style>
		<div class="inner">
			<a href="#" class="image"><div id="map"></div>{# <img src="images/pic02.jpg" alt=""> #}</a>
			<div class="content">
				<h2 class="major">{{ device.human_readable_name }}</h2>
				<table>
					<tr><td>location</td><td>{{ device.location }}</td></tr>
					<tr><td>status</td><td>{{ device.status }}</td></tr>
					<tr><td>description</td><td>{{ device.description_of_device }}</td></tr>
					<tr><td>description of content</td><td>{{ device.description_of_content }}</td></tr>
					<tr><td>last check</td><td>{{ device.last_check_date }}</td></tr>
					<tr><td>type</td><td>{{ device.type_of_device }}</td></tr>
					<tr><td>last check</td><td>{{ device.last_check_date }}</td></tr>
				</table>
				
				<ul class="actions">
				<li><a href="/device/" class="button">Back to All</a></li>
			</ul>
			</div>
			
			<script>
      			function initMap() {
        			var myLatLng = {lat: {{ lat }}, lng: {{ lng }} };

			        var map = new google.maps.Map(document.getElementById('map'), {
          			zoom: 11,
          			center: myLatLng
        			});

        		var marker = new google.maps.Marker({
          			position: myLatLng,
          			map: map,
          			title: '{{ device.human_readable_name }}'
        			});
      			}
    		</script>
			<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAhCCg_frFNc4s65YP-5jaCsnuqGZ9A_A&callback=initMap"></script>
		</div>
	</section>	
{% endblock %}

emCase/device/templates/visual.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Visualization' }} {% endblock %}
{% block content %}
	<section id="two" class="wrapper alt spotlight style2">
		<style>
			#map {
				min-height: 100px;
        		/*height: 100%;*/
        		width: 100%;
        		border-radius: 50%;
      		}
    	</style>
		<div class="inner">
			<a href="#" class="image"><div id="map"></div>{# <img src="images/pic02.jpg" alt=""> #}</a>
			<div class="content">
                <h2>Type of device</h2> 
                {{ type|safe }}

			</div>
		</div>
	</section>	
{% endblock %}

emCase/location/templates/activated.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Location Get' }} {% endblock %}

{% block content %}

	<style>
		#map{
			height: 300px;
			width: 100%;
		}
	</style>

	<section id="one" class="wrapper spotlight style1">
		<div class="inner">
			<div class="content">
                <div id="map"></div>
				<ul class="actions">
				<li><a href="stop" class="button">Deactivate devices</a></li>
			</ul>

                <br />
                <br />
                <h3>Device status</h3>
                {% for key, val in log.items %}

                {{ key  }} : {{ val  }}<br/>
                {% endfor %}
			</div>
			<script>
      			function initMap() {       		
      				var myLatLng = {lat: 50.074029, lng: 14.431704 };
			        var map = new google.maps.Map(document.getElementById('map'), {
          				zoom: 11,
          				center: myLatLng
        			});

				    {% for device_id, vals in devices.items %}
				    	var myLatLng = {lat: {{ vals.lat }}, lng: {{ vals.lng }} };
	        			var marker = new google.maps.Marker({
		          			position: myLatLng,	          				
		          			map: map,
	          				title: '{{ vals.name }}',
	          				{% if vals.type == "MK" %}
	          					icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
	          				{% elif vals.type == "FD" %}
	          				    icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
	          				{% else %}
	          					icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
	          				{% endif %}

	        			});	        			
	        		{% endfor %}
      			}
    		</script>
			<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAhCCg_frFNc4s65YP-5jaCsnuqGZ9A_A&callback=initMap"></script>
		</div>
	</section>	

{% endblock %}

emCase/location/templates/index_location.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Location Index' }} {% endblock %}

{% block content %}

	<style>
		#map{
			height: 300px;
			width: 100%;
		}
	</style>

	<section id="one" class="wrapper spotlight style1">
		<div class="inner">
			<div class="content">
				<p id="map">Click the button to get your position.</p>

				<div id="mapholder"></div>
			</div>
		</div>
	</section>	

<script>
var x = document.getElementById("map");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPositionMap(position) {
    var lat = position.coords.latitude;
    var lng = position.coords.longitude;
	var myLatLng = {lat: lat, lng: lng };

    var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 16,
		center: myLatLng
	});

	var marker = new google.maps.Marker({
			position: myLatLng,
			map: map,
			title: 'Here you are!'
	});
}

function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML = "User denied the request for Geolocation."
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML = "Location information is unavailable."
            break;
        case error.TIMEOUT:
            x.innerHTML = "The request to get user location timed out."
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML = "An unknown error occurred."
            break;
    }
}
</script>
	<div id="demo"></div>
	<script>
		var x = document.getElementById("headderPar");

		function getLocation() {
		    if (navigator.geolocation) {
		        navigator.geolocation.getCurrentPosition(showPosition);
		    } else { 
		        x.innerHTML = "Geolocation is not supported by this browser.";
		    }
		}

		function showPosition(position) {
			showPositionMap(position);
		    x.innerHTML = "Your current position is -- Latitude: " + position.coords.latitude + 
		    ", Longitude: " + position.coords.longitude;	
		}
	</script>
	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAhCCg_frFNc4s65YP-5jaCsnuqGZ9A_A&callback=getLocation"></script>
	<script type="text/javascript">
		/*$(document).ready(function(){ 
			getLocation();
		})*/ 
	</script>
{% endblock %}

emCase/location/templates/loc_form.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Location Get' }} {% endblock %}

{% block content %}

	<style>
		#map{
			height: 300px;
			width: 100%;
		}
		input{
			color: black;
		}
		.emerg_button{
			height: 50px;
			width: 50px;
			font-size: 22pt;
			display: inline-block;
			border-radius: 100%;
    		border: solid 2px rgba(255, 255, 255, 0.125)
    		cursor: all-scroll;
    		display: inline-block;
    		font-size: 3em;
    		height: 2.25em;
    		line-height: 2.25em;
    		text-align: center;
    		width: 2.25em;
		}

		#a{
			font-family: FontAwesome, Helvetica;
			font-size: 2.2em;
		}
		#c{
			font-family: FontAwesome, Helvetica;
			font-size: 2.2em;
		}
		#b{
			font-family: FontAwesome, Helvetica;
			font-size: 2.2em;
		}
	</style>

	<section id="one" class="wrapper spotlight style1">
		<div class="inner">
			<div class="content">
               <form id="emergencyForm" action="" onsubmit="mysubmit();return false" method="post">
                   {% csrf_token %}
                   {{ form }}
               		<br/>               		
               		<br/>       
               		<input id="a" class="fa-input" type="submit" onclick="clicked='FD'" value="&#xf134;" />
               		<input id="b" class="fa-input" type="submit" onclick="clicked='MK'" value="&#xf0fa;" />
               		<input id="c" class="fa-input" type="submit" onclick="clicked='all'" value="&#xf1e2;" />
               </form> 
				<p id="map">Click the button to get your position.</p>

				<div id="mapholder"></div>
			</div>
		</div>
	</section>	
	<script type="text/javascript">
		var clicked;
		function mysubmit() {
			$("#id_command").val("start "+clicked);
    		$("#emergencyForm").submit();
		}		
	</script>
	
<script>
var x = document.getElementById("headderPar");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }
}

function showPositionMap(position) {
    var lat = position.coords.latitude;
    var lng = position.coords.longitude;
	var myLatLng = {lat: lat, lng: lng };

    var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 16,
		center: myLatLng
	});

	var marker = new google.maps.Marker({
			position: myLatLng,
			map: map,
			title: 'Here you are!'
	});
	$("#id_lng").val(lng);
	$("#id_lat").val(lat);
}

function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            x.innerHTML = "User denied the request for Geolocation."
            break;
        case error.POSITION_UNAVAILABLE:
            x.innerHTML = "Location information is unavailable."
            break;
        case error.TIMEOUT:
            x.innerHTML = "The request to get user location timed out."
            break;
        case error.UNKNOWN_ERROR:
            x.innerHTML = "An unknown error occurred."
            break;
    }
}
</script>
	<div id="demo"></div>
	<script>
		var x = document.getElementById("headderPar");

		function getLocation() {
		    if (navigator.geolocation) {
		        navigator.geolocation.getCurrentPosition(showPosition);
		    } else { 
		        x.innerHTML = "Geolocation is not supported by this browser.";
		    }
		}

		function showPosition(position) {
			showPositionMap(position);
		    x.innerHTML = "Your current location is -- Latitude: " + position.coords.latitude + 
		    ", Longitude: " + position.coords.longitude;	
		}
	</script>
	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAhCCg_frFNc4s65YP-5jaCsnuqGZ9A_A&callback=getLocation"></script>
	<script type="text/javascript">
		/*$(document).ready(function(){ 
			getLocation();
		})*/ 
	</script>
{% endblock %}

emCase/location/templates/stop.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Location Get' }} {% endblock %}

{% block content %}

	<style>
		#map{
			height: 300px;
			width: 100%;
		}
	</style>

	<section id="one" class="wrapper spotlight style1">
		<div class="inner">
			<div class="content">
                <h2>
                    Devices stopped
                </h2>
			</div>
		</div>
	</section>	

{% endblock %}

emCase/location/templates/view_location.html
{% extends 'base.html' %}
{% block head_title %} {{ 'Show all locations' }} {% endblock %}
{% block content %}
	<section id="two" class="wrapper alt spotlight style2">
		<style>
			#map {
				min-height: 100px;
        		height: 300px;
        		width: 100%;
      		}
    	</style>
		<div class="inner">
			<div id="map"></div>
			
			<script>
      			function initMap() {       		
      				var myLatLng = {lat: 50.074029, lng: 14.431704 };
			        var map = new google.maps.Map(document.getElementById('map'), {
          				zoom: 11,
          				center: myLatLng
        			});

				    {% for device_id, vals in devices.items %}
				    	var myLatLng = {lat: {{ vals.lat }}, lng: {{ vals.lng }} };
	        			var marker = new google.maps.Marker({
		          			position: myLatLng,	          				
		          			map: map,
	          				title: '{{ vals.name }}',
	          				{% if vals.type == "MK" %}
	          					icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
	          				{% elif vals.type == "FD" %}
	          				    icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
	          				{% else %}
	          					icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
	          				{% endif %}

	        			});	        			
	        		{% endfor %}
      			}
    		</script>
			<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAhCCg_frFNc4s65YP-5jaCsnuqGZ9A_A&callback=initMap"></script>
		</div>
	</section>	
{% endblock %}

emCase/templates/base.html
<!DOCTYPE HTML>
<!--
	Solid State by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
        <title>{% block head_title %} {{ 'Solid State by HTML5 UP' }}{% endblock %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{{ STATIC_URL }}assets/js/ie/html5shiv.js"></script><![endif]-->
        <link rel="stylesheet" href="{{ STATIC_URL }}assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    </script>
	</head>
	<body>

		<!-- Page Wrapper -->
			<div id="page-wrapper">

				<!-- Header -->
					<header id="header" class="alt">
						<h1><a href="index.html">Solid State</a></h1>
						<nav>
							<a href="#menu">Menu</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<div class="inner">
							<h2>Menu</h2>
							<ul class="links">
								<li><a href="/">Home</a></li>
								<li><a href="/device">Device</a></li>
								<li><a href="/location/view_locations">Locations</a></li>
								<li><a href="/device/visual">Visualisation</a></li>
								<li><a href="">Log In</a></li>
								<li><a href="">Sign Up</a></li>
							</ul>
							<a href="#" class="close">Close</a>
						</div>
					</nav>

				<!-- Banner -->
					<section id="banner">
						<div class="inner">
							<div class="logo"><span class="icon fa-medkit"></span></div>
							<h2>Emergency devices</h2>
							<p id="headderPar">All smart emergency devices in the world</p>
						</div>
					</section>

				<!-- Wrapper -->
					<section id="wrapper">
						<div id="demo">
						</div>						
			            {% block content %}
                        {% endblock %}						
					</section>

				<!-- Footer -->
					<section id="footer">
						<div class="inner">
							{% comment %}
							<h2 class="major">Get in touch</h2>
							<p>Cras mattis ante fermentum, malesuada neque vitae, eleifend erat. Phasellus non pulvinar erat. Fusce tincidunt, nisl eget mattis egestas, purus ipsum consequat orci, sit amet lobortis lorem lacus in tellus. Sed ac elementum arcu. Quisque placerat auctor laoreet.</p>
							<form method="post" action="#">
								<div class="field">
									<label for="name">Name</label>
									<input type="text" name="name" id="name" />
								</div>
								<div class="field">
									<label for="email">Email</label>
									<input type="email" name="email" id="email" />
								</div>
								<div class="field">
									<label for="message">Message</label>
									<textarea name="message" id="message" rows="4"></textarea>
								</div>
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</form>
							<ul class="contact">
								<li class="fa-home">
									Untitled Inc<br />
									1234 Somewhere Road Suite #2894<br />
									Nashville, TN 00000-0000
								</li>
								<li class="fa-phone">(000) 000-0000</li>
								<li class="fa-envelope"><a href="#">information@untitled.tld</a></li>
								<li class="fa-twitter"><a href="#">twitter.com/untitled-tld</a></li>
								<li class="fa-facebook"><a href="#">facebook.com/untitled-tld</a></li>
								<li class="fa-instagram"><a href="#">instagram.com/untitled-tld</a></li>
							</ul> 
							{% endcomment %}
							<ul class="copyright">
								<li>&copy; Untitled Inc. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</section>

			</div>

		<!-- Scripts -->
			<script src="{{ STATIC_URL }}assets/js/skel.min.js"></script>
			<script src="{{ STATIC_URL }}assets/js/jquery.min.js"></script>
			<script src="{{ STATIC_URL }}assets/js/jquery.scrollex.min.js"></script>
			<script src="{{ STATIC_URL }}assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="{{ STATIC_URL }}assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{{ STATIC_URL }}assets/js/main.js"></script>

	</body>
</html>